Repository flyve-mdm/web-mdm-dashboard, pull requests merged in 2018-05, with the labels that each got.

#777 JavaScript License Web Labels
  public/index.html
Labels: documentation

#779 Validate HTML
  .circleci/config.yml
  ci/scripts/install.sh
Labels: ci, test

#782 Generate sitemap
  ci/scripts/install.sh
  ci/scripts/sitemap_generator.sh
  gitlabRunner.sh
Labels: build, ci

#786 Unnecessary requests
  src/components/Forms/Select/index.js
Labels: bug, performance

#791 Fix update Breadcrumb
  src/components/HeaderBreadcrumb/index.js
  src/components/SplitView/index.js
  src/hoc/withAdminDashboardLayout/index.js
Labels: bug

#796 Avoid minify the config file
  .gitignore
  ci/scripts/create_config_file.sh
  config/env.js
  config/webpack.config.dev.js
  config/webpack.config.prod.js
  public/config.example.json
  public/config.json
  src/components/ValidateAccount/index.js
  src/containers/Settings/components/Security/index.js
  src/containers/SignIn/components/UsernameFieldset.js
  src/shared/glpiApi.js
  src/store/authentication/actions.js
Labels: ci, refactor

#801 Software request
  src/config/config.json
  src/containers/Devices/components/Sections/Applications.js
  yarn.lock
Labels: refactor

#803 Problems with the fleets list
  src/containers/Fleets/components/FleetsList.js
Labels: bug

#811 Add professional services
  README.md
Labels: documentation

#813 Applications details
  src/containers/Devices/components/Sections/Applications/ApplicationDetail.js
  src/containers/Devices/components/Sections/Applications/index.js
Labels: bug, refactor

#823 Gitlab dependencies
  gitlabRunner.sh
Labels: bug, ci

#826 Small changes in the feedback screen
  src/assets/styles/architecture/5_level_components/_about.scss
  src/components/Forms/TextArea/index.js
  src/containers/About/components/HelpCenter/Feedback.js
  src/hoc/withI18NTranslation/i18n/source_file.json
Labels: bug, refactor

#829 Add deleted htaccess
  htaccess_dev
Labels: bug

#840 Fix documentation of 'withHandleMessages'
  src/hoc/withHandleMessages/index.js
Labels: bug, documentation

#847 Deploy application - sonarwhal error
  .circleci/config.yml
Labels: bug, ci

#848 Delete unnecessary element
  _includes/header.html
Labels: documentation

#852 Add headers to coverage
  .circleci/config.yml
  ci/scripts/add_header.rb
  ci/scripts/add_header.sh
  ci/scripts/deploy_develop.sh
  ci/scripts/install.sh
Labels: ci, test

#854 Fix the conflict of the double key in Jekyll
  ci/scripts/add_space.rb
  ci/scripts/deploy_develop.sh
Labels: bug, ci, test

#856 Code documentation to shared modules
  src/shared/BuildItemList/index.js
  src/shared/animations/index.js
  src/shared/animationsWinJs/index.js
  src/shared/authtype/index.js
  src/shared/bytesToSize/index.js
  src/shared/calc100PercentMinus/index.js
  src/shared/configureDisplay/index.js
  src/shared/cookies/index.js
  src/shared/getID/index.js
  src/shared/getMode/index.js
  src/shared/glpiApi/index.js
  src/shared/handleMessage/index.js
  src/shared/history/index.js
  src/shared/itemtype/index.js
  src/shared/logout/index.js
  src/shared/nativeNotification/index.js
  src/shared/publicURL/index.js
  src/shared/setGlpiCookie/index.js
  src/shared/toDateInputValue/index.js
  src/shared/updateObject/index.js
  src/shared/validateData/index.js
  src/shared/validateDate/index.js
  src/shared/validateNotifications/index.js
Labels: documentation

#857 Documentation of the high order components
  src/hoc/withAdminDashboardLayout/index.js
  src/hoc/withAsyncComponent/index.js
  src/hoc/withAuthenticationLayout/index.js
  src/hoc/withGLPI/index.js
  src/hoc/withHandleMessages/index.js
  src/hoc/withI18NTranslation/index.js
  src/hoc/withNotification/index.js
Labels: documentation
