Repository flyve-mdm/web-mdm-dashboard, pull requests merged in 2018-03, with the labels that each got.

#393 Add routes and refactoring
  src/AdminDashboard/About/Contact.js
  src/applications/RootApp/index.js
  src/assets/styles/architecture/1_level_settings/.gitkeep
  src/assets/styles/architecture/1_level_settings/_colors.scss
  src/assets/styles/architecture/1_level_settings/_sizes.scss
  src/assets/styles/architecture/2_level_tools/.gitkeep
  src/assets/styles/architecture/2_level_tools/_mq.scss
  src/assets/styles/architecture/2_level_tools/_placeholders.scss
  src/assets/styles/architecture/3_level_generic/.gitkeep
  src/assets/styles/architecture/3_level_generic/_animations.scss
  src/assets/styles/architecture/3_level_generic/_normalize.scss
  src/assets/styles/architecture/4_level_elements/.gitkeep
  src/assets/styles/architecture/4_level_elements/_body_font_size.scss
  src/assets/styles/architecture/4_level_elements/_main.scss
  src/assets/styles/architecture/5_level_components/.gitkeep
  src/assets/styles/architecture/5_level_components/_authentication_layout.scss
  src/assets/styles/architecture/5_level_components/_btn.scss
  src/assets/styles/architecture/5_level_components/_layout_list_with_navlinks.scss
  src/assets/styles/architecture/5_level_components/_select_language.scss
  src/assets/styles/architecture/5_level_components/_splitview.scss
  src/assets/styles/architecture/6_level_utilities/.gitkeep
  src/assets/styles/main.scss
  src/async/asyncAdminDashboard.js
  src/components/GenerateRoutes/index.js
  src/components/InfoBox/index.js
  src/components/SplitView/index.js
  src/components/ValidateAccount/index.js
  src/containers/About/components/Contact/index.js
  src/containers/About/components/HelpCenter/Feedback.js
  src/containers/About/components/HelpCenter/HelpCenterArticle.js
  src/containers/About/components/HelpCenter/HelpCenterList.js
  src/containers/About/components/HelpCenter/articles/article_1.md
  src/containers/About/components/HelpCenter/articles/article_2.md
  src/containers/About/components/HelpCenter/articles/article_3.md
  src/containers/About/components/HelpCenter/articles/article_4.md
  src/containers/About/components/HelpCenter/articles/article_5.md
  src/containers/About/components/HelpCenter/articles/article_6.md
  src/containers/About/components/HelpCenter/index.js
  src/containers/About/components/HelpCenter/routes.js
  src/containers/About/components/License/LICENCE.md
  src/containers/About/components/License/index.js
  src/containers/About/components/Overview/index.js
  src/containers/About/components/ReleaseNotes/CHANGELOG.md
  src/containers/About/components/ReleaseNotes/index.js
  src/containers/About/components/SystemInformation/index.js
  src/containers/About/components/TermsOfUse/index.js
  src/containers/About/routes.js
  src/containers/ForgotPassword/index.js
  src/containers/SignIn/index.js
  src/data/helpCenter.json
  src/data/plugins.json
  src/hoc/withToastNotification/index.js
  src/store/authentication/actions.js
Labels: refactor

#399 Fix styles
  src/applications/AdminDashboardApp/index.js
  src/applications/AdminDashboardApp/routes.js
  src/applications/RootApp/index.js
  src/assets/styles/architecture/1_level_settings/_colors.scss
  src/assets/styles/architecture/1_level_settings/_sizes.scss
  src/assets/styles/architecture/2_level_tools/_mq.scss
  src/assets/styles/architecture/3_level_generic/_normalize.scss
  src/assets/styles/architecture/4_level_elements/_a.scss
  src/assets/styles/architecture/4_level_elements/_body.scss
  src/assets/styles/architecture/4_level_elements/_input_and_textarea.scss
  src/assets/styles/architecture/5_level_components/_about.scss
  src/assets/styles/architecture/5_level_components/_normalize.scss
  src/assets/styles/architecture/5_level_components/_splitview.scss
  src/assets/styles/architecture/6_level_utilities/_popper.scss
  src/styles/architecture/1_level_settings/.gitkeep
  src/styles/architecture/1_level_settings/_breakpoints.scss
  src/styles/architecture/1_level_settings/_colors.scss
  src/styles/architecture/1_level_settings/_sizes.scss
  src/styles/architecture/2_level_tools/.gitkeep
  src/styles/architecture/2_level_tools/_mixins.scss
  src/styles/architecture/2_level_tools/_mq.scss
  src/styles/architecture/2_level_tools/_placeholders.scss
  src/styles/architecture/3_level_generic/.gitkeep
  src/styles/architecture/3_level_generic/_animations.scss
  src/styles/architecture/3_level_generic/_normalize.scss
  src/styles/architecture/4_level_elements/.gitkeep
  src/styles/architecture/4_level_elements/_body_font_size.scss
  src/styles/architecture/5_level_components/.gitkeep
  src/styles/architecture/5_level_components/_about.scss
  src/styles/architecture/5_level_components/_applications.scss
  src/styles/architecture/5_level_components/_authentication_layout.scss
  src/styles/architecture/5_level_components/_btn.scss
  src/styles/architecture/5_level_components/_dashboard.scss
  src/styles/architecture/5_level_components/_devices.scss
  src/styles/architecture/5_level_components/_errors.scss
  src/styles/architecture/5_level_components/_files.scss
  src/styles/architecture/5_level_components/_fleets.scss
  src/styles/architecture/5_level_components/_header_admin_dashboard.scss
  src/styles/architecture/5_level_components/_icons.scss
  src/styles/architecture/5_level_components/_invitations.scss
  src/styles/architecture/5_level_components/_loading.scss
  src/styles/architecture/5_level_components/_search_engine.scss
  src/styles/architecture/5_level_components/_select_language.scss
  src/styles/architecture/5_level_components/_settings.scss
  src/styles/architecture/5_level_components/_splitview.scss
  src/styles/architecture/5_level_components/_title.scss
  src/styles/architecture/5_level_components/_toast.scss
  src/styles/architecture/5_level_components/_users.scss
  src/styles/architecture/6_level_utilities/.gitkeep
  src/styles/architecture/6_level_utilities/_popper.scss
  src/styles/architecture/6_level_utilities/_ui-light.scss
  src/styles/main.scss
Labels: bug, style

#400 GLPI HOC
  src/hoc/withGLPI/index.js
Labels: refactor

#403 Improve Settings Page
  .tx/config
  src/assets/styles/main.scss
  src/containers/Settings/components/Display/index.js
  src/containers/Settings/components/Entity/ChangeDownloadURL.js
  src/containers/Settings/components/Entity/ChangeTokenLife.js
  src/containers/Settings/components/Profiles/index.js
  src/containers/Settings/components/Security/index.js
  src/containers/Settings/components/Supervision/index.js
  src/hoc/withToastNotification/index.js
  src/store/authentication/actionTypes.js
  src/store/authentication/actions.js
  src/store/authentication/reducer.js
  src/store/ui/actionTypes.js
  src/store/ui/actions.js
  src/store/ui/initialState.js
  src/store/ui/reducer.js
Labels: feature, refactor

#425 Colors in the menu
  src/assets/styles/architecture/5_level_components/_listpane.scss
Labels: refactor

#427 Fix typo in title
  _posts/static/2017-12-26-how-to-contribute.md
Labels: documentation

#430 Center loading
  src/assets/styles/architecture/5_level_components/_authentication_layout.scss
  src/assets/styles/architecture/5_level_components/_listPane.scss
  src/assets/styles/architecture/5_level_components/_listpane.scss
  src/assets/styles/main.scss
Labels: refactor

#439 Win-dropdown
  src/assets/styles/architecture/1_level_settings/_colors.scss
  src/assets/styles/architecture/6_level_utilities/_win_dropdown.scss
  src/assets/styles/main.scss
Labels: refactor

#449 Update contributing guidelines
  CONTRIBUTING.md
Labels: documentation

#451 Add ITCSS specifications
  CONTRIBUTING.md
Labels: documentation

#457 Devices content vertical scroll
  src/assets/styles/architecture/5_level_components/_fleets.scss
  src/assets/styles/architecture/6_level_utilities/_win_pivot_viewport.scss
  src/assets/styles/main.scss
Labels: refactor

#463 Background color of the list menu
  src/assets/styles/architecture/1_level_settings/_colors.scss
  src/assets/styles/architecture/5_level_components/_listpane.scss
Labels: refactor

#465 Responsive design of the forms
  src/assets/styles/architecture/5_level_components/_froms.scss
Labels: refactor

#495 Update bots list in contributing file
  CONTRIBUTING.md
Labels: documentation

#499 Multiple edits for devices
  src/containers/Devices/components/DevicesEdit.js
  src/containers/Devices/components/DevicesEditOne.js
Labels: refactor

#503 Dashboard data
  src/assets/styles/architecture/4_level_elements/_main.scss
  src/assets/styles/architecture/6_level_utilities/_flex_container.scss
  src/containers/HomeDashboard/index.js
Labels: feature

#501 Resend invitations
  src/containers/Invitations/components/InvitationsList.js
Labels: feature

#506 Loading component in the profile
  src/containers/Settings/components/Profiles/index.js
Labels: refactor

#508 Search button of the Help Center
  src/containers/About/components/HelpCenter/HelpCenterList.js
Labels: bug

#512 Duplicate headers
  src/containers/Settings/components/Entity/ChangeDownloadURL.js
  src/containers/Settings/components/Entity/ChangeTokenLife.js
  src/containers/Settings/components/Entity/Main.js
Labels: bug, refactor

#514 Styles of add application page
  src/assets/styles/architecture/5_level_components/_file_upload.scss
  src/containers/Applications/components/ApplicationsAdd.js
Labels: refactor

#527 Fix go to main route on Fleets screen
  src/containers/Fleets/index.js
Labels: bug

#551 Add new file header
  src/containers/Files/components/FilesAdd.js
Labels: refactor

#547 Improve getting started article
  _posts/static/2018-01-18-getting-started.md
Labels: documentation

#556 Pending invitations card
  src/containers/HomeDashboard/index.js
Labels: bug
