Repository flyve-mdm/web-mdm-dashboard, pull requests merged in 2018-09, with the labels that each got.

#1080 Format the error messages
  src/shared/handleMessage/index.js
Labels: refactor

#1084 Fix typo in documentation
  _posts/static/2017-12-26-how-to-contribute.md
Labels: documentation

#1086 Fix upload of applications
  src/containers/Applications/components/ApplicationsAdd.js
Labels: bug, refactor

#1088 Fix set docs destination
  .circleci/config.yml
  ci/scripts/coverage.sh
  ci/scripts/documentation.sh
Labels: bug

#1107 Fix link to development documentation
  _includes/header.html
Labels: documentation

#1110 Fix images paths on the project site
  _includes/image-WebP.html
Labels: bug, documentation

#1111 Fix the image path on the project site footer
  _includes/footer.html
Labels: bug, documentation
