Repository flyve-mdm/web-mdm-dashboard, pull requests merged in 2018-04, with the labels that each got.

#565 Show tooltip when select icon menu
  src/components/ImageResponsive/index.js
  src/components/SplitView/IconWithPopper/index.js
  src/components/SplitView/imgWithPopper/index.js
Labels: feature

#571 Follow JSON Style Guide for the config file
  src/config/config.json
  src/containers/Settings/components/Security/index.js
  src/containers/SignIn/components/UsernameFieldset.js
  src/shared/glpiApi.js
  src/store/authentication/actions.js
Labels: style

#570 Supervision data
  src/containers/Settings/components/Supervision/index.js
Labels: feature, refactor

#574 System information data
  src/containers/About/components/SystemInformation/index.js
Labels: feature

#578 Get captcha
  src/shared/itemtype.js
Labels: bug

#580 Incorrect title on the register page
  src/hoc/withI18NTranslation/i18n/source_file.json
Labels: bug

#581 Error when registering a user
  src/shared/itemtype.js
Labels: bug

#583 Continuous Deployment using GitLab CI
  .gitlab-ci.yml
  ci/scripts/copy_build.sh
Labels: ci

#584 Missing item types
  src/shared/itemtype.js
Labels: bug

#587 Use npm to build GitLab CI
  .gitlab-ci.yml
Labels: ci

#588 Change npm to yarn
  .gitlab-ci.yml
Labels: build, ci

#589 Add copy folder command
  .gitlab-ci.yml
Labels: bug, ci

#590 Leaflet resources should use the same protocol
  public/index.html
Labels: bug

#591 Add temp home URL for testing purpose
  package.json
Labels: build

#594 Leaflet css
  public/css/leaflet.css
  public/images/layers-2x.png
  public/images/layers.png
  public/images/marker-icon-2x.png
  public/images/marker-icon.png
  public/images/marker-shadow.png
  public/index.html
Labels: refactor

#596 Remove service worker
  src/index.js
Labels: refactor

#597 Unregister service worker
  src/index.js
Labels: refactor

#602 Remove slash (/) route homepage
  package.json
Labels: refactor

#603 Update date in the footer
  src/components/NotFound/index.js
  src/hoc/withAuthenticationLayout/index.js
Labels: refactor

#605 Dashboard images
  config/webpack.config.dev.js
  config/webpack.config.prod.js
  public/images/profile/221_5a084effc6624.jpg
  public/images/profile/222_5a084effc6624.jpg
  public/images/profile/223_5a084effc6624.jpg
  public/images/profile/224_5a084effc6624.jpg
  public/images/profile/225_5a084effc6624.jpg
  public/images/profile/226_5a084effc6624.jpg
  public/images/profile/227_5a084effc6624.jpg
  public/images/profile/2_5a084ec9dd7ef.png
  public/images/screen1.png
  public/images/shema01.png
  src/assets/images/Clipboard.png
  src/assets/images/Facebook.svg
  src/assets/images/GitHub.png
  src/assets/images/GooglePlus.svg
  src/assets/images/PaperPlane.png
  src/assets/images/Phone.png
  src/assets/images/Reddit.svg
  src/assets/images/Telegram.svg
  src/assets/images/Twitter.svg
  src/assets/images/android.png
  src/assets/images/apple.png
  src/assets/images/dashboard.svg
  src/assets/images/icon-192x192.png
  src/assets/images/icon-256x256.png
  src/assets/images/icon-384x384.png
  src/assets/images/icon-512x512.png
  src/assets/images/logo-teclib.png
  src/assets/images/logo.png
  src/assets/images/logo2.png
  src/assets/images/logout.png
  src/assets/images/profile.png
  src/assets/images/typo.png
  src/components/IconItemList/index.js
  src/components/ImageResponsive/index.js
  src/components/NotFound/index.js
  src/components/SplitView/index.js
  src/containers/About/components/Contact/index.js
  src/containers/Settings/components/Profiles/index.js
  src/hoc/withAuthenticationLayout/index.js
Labels: bug

#612 Refresh list after item update
  src/components/MenuListWinJs/index.js
  src/containers/Applications/components/ApplicationsAdd.js
  src/containers/Applications/components/ApplicationsContent.js
  src/containers/Applications/components/ApplicationsEdit.js
  src/containers/Applications/components/ApplicationsList.js
  src/containers/Devices/components/DevicesList.js
  src/containers/Devices/components/Enroll.js
  src/containers/Devices/components/Sections/DangerZone.js
  src/containers/Files/components/FilesAdd.js
  src/containers/Files/components/FilesContent.js
  src/containers/Files/components/FilesEdit.js
  src/containers/Files/components/FilesList.js
  src/containers/Fleets/components/FleetsContent.js
  src/containers/Fleets/components/FleetsList.js
  src/containers/Invitations/components/InvitationsList.js
  src/containers/Users/components/UsersContent.js
  src/containers/Users/components/UsersList.js
Labels: refactor

#614 Streaming Leaflet Tiles over HTTPS / SSL
  src/containers/Devices/components/Map.js
Labels: bug

#615 Home cards
  src/containers/HomeDashboard/index.js
Labels: bug

#616 Fix menu links
  src/components/SplitView/index.js
Labels: bug

#618 Image import errors in IconItemList
  src/components/IconItemList/index.js
Labels: bug

#620 Icon for native notifications
  public/images/dashboard.png
  src/shared/nativeNotification.js
Labels: bug

#622 Notifications icon path
  src/shared/nativeNotification.js
Labels: bug

#642 Show geocalations
  src/containers/Devices/components/Map.js
  src/containers/Devices/components/Sections/Geolocation.js
  src/containers/Devices/components/Sections/GeolocationList.js
  src/shared/itemtype.js
Labels: bug

#643 Height of the map
  src/containers/Devices/components/Map.js
Labels: refactor

#645 Validate not allow empty values
  src/containers/Fleets/components/FleetsTaskItemList.js
Labels: bug, refactor

#651 Fix redirect for sign in page
  src/components/ValidateAccount/index.js
Labels: bug

#656 Wrong language name
  src/containers/Settings/components/Display/index.js
  src/hoc/withAuthenticationLayout/index.js
  src/hoc/withI18NTranslation/i18n/source_file.json
Labels: bug

#659 Change password
  src/containers/Settings/components/Security/index.js
  src/store/ui/reducer.js
Labels: bug

#667 Without permits for the fleet
  src/containers/Fleets/components/FleetsContent.js
Labels: bug

#669 Transifex automatic update
  .gitlab-ci.yml
Labels: ci

#678 Fix update value tasks dropdown type
  src/containers/Fleets/components/FleetsTaskItemList.js
Labels: bug

#679 Data of the home page
  src/containers/HomeDashboard/index.js
Labels: bug, refactor

#680 Singular / plural names
  src/containers/HomeDashboard/index.js
  src/hoc/withI18NTranslation/i18n/source_file.json
Labels: refactor

#682 Base URL in dev configuration
  config/webpack.config.dev.js
  src/applications/RootApp/routes.js
  src/components/HeaderBreadcrumb/index.js
  src/components/MenuListWinJs/index.js
  src/components/SplitView/index.js
  src/components/ValidateAccount/index.js
  src/containers/About/components/HelpCenter/HelpCenterList.js
  src/containers/Applications/components/ApplicationsContent.js
  src/containers/Applications/components/ApplicationsList.js
  src/containers/Applications/index.js
  src/containers/Devices/components/DevicesList.js
  src/containers/Devices/components/Sections/DangerZone.js
  src/containers/Devices/components/Sections/Geolocation.js
  src/containers/Devices/components/Sections/Main.js
  src/containers/Devices/index.js
  src/containers/Files/components/FilesContent.js
  src/containers/Files/components/FilesList.js
  src/containers/Files/index.js
  src/containers/Fleets/components/FleetsList.js
  src/containers/Fleets/index.js
  src/containers/ForgotPassword/index.js
  src/containers/HomeDashboard/index.js
  src/containers/Invitations/components/InvitationsList.js
  src/containers/Invitations/index.js
  src/containers/ResetPassword/index.js
  src/containers/SignIn/components/PasswordFieldset.js
  src/containers/SignIn/components/UsernameFieldset.js
  src/containers/SignIn/index.js
  src/containers/SignUp/index.js
  src/containers/Users/components/UsersContent.js
  src/containers/Users/components/UsersList.js
  src/containers/Users/index.js
  src/shared/getID.js
  src/shared/handleMessage.js
  src/shared/location.js
  src/shared/nativeNotification.js
  src/shared/publicURL.js
  src/store/authentication/reducer.js
Labels: bug, build

#683 Show always main content on Fleets
  src/containers/Fleets/components/FleetsContent.js
Labels: refactor

#681 Update Transifex integration
  .gitlab-ci.yml
Labels: ci

#687 Devices currently managed on the homepage
  src/containers/HomeDashboard/index.js
Labels: bug

#692 Entity data
  src/containers/Settings/components/Entity/index.js
Labels: refactor

#696 User deletion
  src/containers/Users/components/UsersContent.js
Labels: bug

#698 Fix get pathname from PUBLIC_URL
  src/shared/publicURL.js
Labels: bug

#705 Fix scroll content on Fleets
  src/containers/Fleets/components/FleetsContent.js
Labels: refactor

#708 Fix scroll content on Chrome
  src/containers/Fleets/components/FleetsContent.js
Labels: refactor

#715 Allow connections https
  public/index.html
Labels: bug

#720 Fix show message confirmation
  src/components/SplitView/index.js
  src/hoc/withAdminDashboardLayout/index.js
Labels: bug

#723 Fix show mixed content
  src/hoc/withAdminDashboardLayout/index.js
Labels: bug

#727 GLPI cookies
  src/shared/cookies.js
  src/shared/setGlpiCookie.js
Labels: bug

#742 SplitView animation
  src/assets/styles/architecture/5_level_components/_splitview.scss
  src/components/SplitView/index.js
  src/hoc/withAdminDashboardLayout/index.js
  src/shared/animations.js
Labels: refactor

#743 Animation to sign in
  src/containers/SignIn/index.js
  src/shared/animations.js
Labels: feature

#749 Improve fleet information
  src/assets/styles/architecture/5_level_components/_fleets.scss
  src/containers/Fleets/components/FleetsContent.js
Labels: feature, refactor

#755 Device requests
  src/containers/Devices/components/DevicesContent.js
  src/containers/Devices/components/Sections/Applications.js
  src/containers/Devices/components/Sections/DangerZone.js
  src/containers/Devices/components/Sections/Geolocation.js
  src/containers/Devices/components/Sections/Inventory.js
  src/containers/Devices/components/Sections/Main.js
  src/containers/Devices/components/Sections/SystemReport.js
Labels: bug, performance

#756 Agent list improvements
  src/components/ContentPane/index.js
  src/containers/Devices/components/Sections/DangerZone.js
  src/shared/animations.js
Labels: feature

#758 Show the map of geolocation correctly
  src/containers/Devices/components/Sections/Geolocation.js
Labels: bug

#759 Improve logout in settings
  src/containers/Settings/components/Security/index.js
Labels: refactor
