Repository flyve-mdm/web-mdm-dashboard, pull requests merged in 2018-08, with the labels that each got.

#1034 Add docker compatibility
  README.md
Labels: documentation

#1035 Add ci documentation
  ci/README.md
Labels: documentation

#1036 Fix gh-pages vulnerabilities
  package-lock.json
  package.json
Labels: bug, documentation

#1069 'Howtos' in safari
  pages/howtos.html
Labels: documentation, refactor

#1068 Projects list of gh-pages
  _sass/5_level_components/_projects.scss
  _sass/6_level_utilities/_jumbotron.scss
  css/main.scss
  pages/projects.html
Labels: documentation, refactor

#1070 Footer adaptive for the project site
  _layouts/container.html
  _sass/4_level_elements/_html.scss
  _sass/5_level_components/_container__page.scss
  css/main.scss
Labels: documentation, refactor

#1071 Howtos header
  _layouts/howtos.html
  pages/howtos.html
Labels: documentation, refactor

#1072 Update readme
  README.md
Labels: documentation
