Repository flyve-mdm/web-mdm-dashboard, pull requests merged in 2018-10, with the labels that each got.

#1119 Search engine multilanguage
  src/containers/SearchEngine/components/QueryBuilder/Rule.js
  src/containers/SearchEngine/components/QueryBuilder/index.js
  src/shared/glpiApi/__test__/glpiApi.spec.js
  src/shared/i18n/source_file.json
Labels: hacktoberfest, refactor

#1126 Pin react-scripts to 2.0.4
  package.json
Labels: build

#1129 CHANGELOG on gh-pages
  package.json
Labels: ci, documentation

#1130 Update danger zone information
  _posts/static/2018-01-17-use-cases.md
  _posts/static/2018-01-19-getting-started.md
Labels: documentation

#1152 Geolocation filter margins
  src/assets/styles/architecture/5_level_components/_geolocation.scss
  src/assets/styles/main.scss
  src/containers/Devices/components/Sections/Geolocation.js
  src/containers/Devices/components/Sections/GeolocationList.js
  yarn.lock
Labels: refactor

#1153 Profile picture
  src/containers/Settings/components/Profiles/index.js
Labels: refactor

#1154 Multiple edition form
  src/components/ContentPane/index.js
  src/components/EditMultiple/index.js
Labels: refactor
