Repository flyve-mdm/web-mdm-dashboard, pull requests merged in 2018-06, with the labels that each got.

#862 Code documentation to Routes
  src/applications/AdminDashboard/index.js
  src/applications/AdminDashboard/routes.js
  src/applications/RootApp/index.js
  src/applications/RootApp/routes.js
Labels: documentation

#864 Code documentation to asynchronous components
  src/async/asyncAdminDashboard.js
  src/async/asyncForgotPassword.js
  src/async/asyncLogout.js
  src/async/asyncPasswordFielset.js
  src/async/asyncResetPassword.js
  src/async/asyncSignUp.js
  src/async/asyncValidateAccount.js
Labels: documentation

#874 Self-registration link in errors of login
  src/containers/SignIn/components/UsernameFieldset.js
Labels: bug

#886 Bad display of the title on the profile page
  src/containers/Settings/components/Profiles/index.js
Labels: refactor

#884 Loading of the help center wrong centered
  src/containers/About/components/HelpCenter/HelpCenterList.js
Labels: refactor

#882 Improve internal scrolls
  src/assets/styles/architecture/2_level_tools/_placeholders.scss
  src/assets/styles/architecture/5_level_components/_navlinks.scss
  src/assets/styles/architecture/6_level_utilities/_flex_container.scss
  src/components/LayoutListWithNavLinks/__tests__/__snapshots__/LayoutListWithNavLinks.snapshot.js.snap
  src/components/LayoutListWithNavLinks/index.js
Labels: refactor

#888 Languages list
  src/containers/Settings/components/Display/index.js
  src/hoc/withAuthenticationLayout/index.js
  src/hoc/withI18NTranslation/i18n/languages.js
  src/hoc/withI18NTranslation/i18n/source_file.json
Labels: feature

#892 Validate item ID is number on Fleets
  src/containers/Fleets/components/FleetsContent.js
Labels: bug

#895 Device ID on the danger zone
  src/containers/Devices/components/DevicesContent.js
Labels: bug

#897 Add docker for develop
  docker/.env
  docker/docker-compose.yml
  docker/docker/node/Dockerfile
Labels: feature

#901 Fix the multiple selection
  src/containers/Applications/index.js
  src/containers/Devices/index.js
  src/containers/Files/index.js
  src/containers/Fleets/index.js
  src/containers/Invitations/index.js
  src/containers/Users/index.js
Labels: bug, dependent

#904 Refactoring the user code with the rules of Airbnb
  src/components/EditMultiple/index.js
  src/components/IconItemList/index.js
  src/containers/Users/components/UsersContent.js
  src/containers/Users/components/UsersEdit.js
  src/containers/Users/components/UsersEditOne.js
  src/containers/Users/components/UsersItemList.js
  src/containers/Users/components/UsersList.js
  src/containers/Users/index.js
  src/containers/Users/routes.js
Labels: refactor, style

#908 Refactoring the sign-in code with the rules of Airbnb
  src/containers/SignIn/actions.js
  src/containers/SignIn/components/PasswordFieldset.js
  src/containers/SignIn/components/UsernameFieldset.js
  src/containers/SignIn/index.js
Labels: style

#911 Error of the login form animation
  src/containers/SignIn/index.js
Labels: bug

#914 Refactoring the searchEngine code with the rules of Airbnb
  src/containers/SearchEngine/actions.js
  src/containers/SearchEngine/components/Panel/PanelFields.js
  src/containers/SearchEngine/components/Panel/PanelResults.js
  src/containers/SearchEngine/components/Panel/index.js
  src/containers/SearchEngine/components/SearchQueryBuilder.js
  src/containers/SearchEngine/index.js
Labels: style

#916 Refactoring the invitations code with the rules of Airbnb
  src/containers/Invitations/components/InvitationsItemList.js
  src/containers/Invitations/components/InvitationsList.js
  src/containers/Invitations/components/InvitationsPendingPage.js
  src/containers/Invitations/index.js
  src/containers/Invitations/routes.js
Labels: style

#918 Refactoring the forgot-password with the rules of Airbnb
  src/containers/ForgotPassword/index.js
Labels: style

#917 Refactoring the home with the rules of Airbnb
  src/containers/HomeDashboard/index.js
Labels: style

#919 Refactoring the files with the rules of Airbnb
  src/containers/Files/components/FilesAdd.js
  src/containers/Files/components/FilesContent.js
  src/containers/Files/components/FilesEdit.js
  src/containers/Files/components/FilesEditItemList.js
  src/containers/Files/components/FilesItemList.js
  src/containers/Files/components/FilesList.js
  src/containers/Files/index.js
  src/containers/Files/routes.js
Labels: style

#920 Refactoring the applications with the rules of Airbnb
  src/containers/Applications/components/ApplicationsAdd.js
  src/containers/Applications/components/ApplicationsContent.js
  src/containers/Applications/components/ApplicationsEdit.js
  src/containers/Applications/components/ApplicationsEditItemList.js
  src/containers/Applications/components/ApplicationsItemList.js
  src/containers/Applications/components/ApplicationsList.js
  src/containers/Applications/index.js
  src/containers/Applications/routes.js
Labels: style

#923 Refactoring the fleets with the rules of Airbnb
  src/containers/Fleets/components/DevicesAssociated.js
  src/containers/Fleets/components/FleetsContent.js
  src/containers/Fleets/components/FleetsEdit.js
  src/containers/Fleets/components/FleetsItemList.js
  src/containers/Fleets/components/FleetsList.js
  src/containers/Fleets/components/FleetsTaskItemList.js
  src/containers/Fleets/components/TaskDeployFileList.js
  src/containers/Fleets/components/TasksDeployAppList.js
  src/containers/Fleets/components/TasksRemoveAppList.js
  src/containers/Fleets/components/TasksRemoveFileList.js
  src/containers/Fleets/index.js
  src/containers/Fleets/routes.js
  src/containers/ResetPassword/actions.js
  src/containers/ResetPassword/index.js
Labels: style

#915 Refactoring the reset-password with the rules of Airbnb
  .eslintignore
  .eslintrc.json
  src/containers/ResetPassword/actions.js
  src/containers/ResetPassword/index.js
Labels: style

#910 Refactoring the sign-up code with the rules of Airbnb
  src/containers/SignUp/actions.js
  src/containers/SignUp/index.js
Labels: style

#924 ForgotPassword placeholder
  cypress/integration/Fleets.spec.js
  cypress/screenshots/fleets_content.png
  src/containers/ForgotPassword/index.js
  src/hoc/withI18NTranslation/i18n/source_file.json
Labels: refactor
