Repository flyve-mdm/web-mdm-dashboard, pull requests merged in 2018-12, with the labels that each got.

#1202 Update dependencies
  package.json
  yarn.lock
Labels: build

#1209 Documentation on the CI
  src/components/EditMultiple/index.js
  src/components/Forms/ConstructInputs/index.js
  src/components/SplitView/index.js
  src/containers/About/components/HelpCenter/Feedback.js
  src/containers/About/components/HelpCenter/index.js
  src/containers/Applications/components/ApplicationsList.js
  src/containers/Applications/index.js
  src/containers/Devices/components/DevicesContent.js
  src/containers/Devices/components/DevicesList.js
  src/containers/Devices/components/Sections/Applications/index.js
  src/containers/Devices/components/Sections/DangerZone.js
  src/containers/Devices/components/Sections/GeolocationRange.js
  src/containers/Devices/components/Sections/Inventory.js
  src/containers/Devices/components/Sections/SystemReport.js
  src/containers/Devices/index.js
  src/containers/Files/components/FilesAdd.js
  src/containers/Files/components/FilesList.js
  src/containers/Files/index.js
  src/containers/Fleets/components/DevicesAssociated.js
  src/containers/Fleets/components/FleetsContent.js
  src/containers/Fleets/components/FleetsList.js
  src/containers/Fleets/index.js
  src/containers/ForgotPassword/index.js
  src/containers/Invitations/components/InvitationsList.js
  src/containers/Invitations/index.js
  src/containers/ResetPassword/index.js
  src/containers/SearchEngine/components/QueryBuilder/Rule.js
  src/containers/Settings/components/Entity/Main.js
  src/containers/Settings/components/Entity/index.js
  src/containers/Settings/components/Profiles/index.js
  src/containers/Settings/components/Security/index.js
  src/containers/Users/components/UsersContent.js
  src/containers/Users/components/UsersList.js
  src/providers/NotificationsProvider/index.js
Labels: bug, ci, documentation

#1211 Update 'eslint-plugin-jsx-a11y'
  package.json
  yarn.lock
Labels: build

#1217 Network and storages information
  src/containers/Devices/components/Sections/Inventory.js
  src/containers/Devices/components/Sections/SystemReport.js
  src/shared/i18n/source_file.json
Labels: feature

#1222 Delete ChangeLog
  CHANGELOG.md
Labels: documentation
