Repository flyve-mdm/web-mdm-dashboard, pull requests merged in 2018-02, with the labels that each got.

#301 Circle CI & Transifex Integration
  .gitignore
  .tx/config
  circle.yml
  package.json
  src/Login/DuckController.js
  src/Login/LoginContainer.js
  src/Login/SingUp/LoginUsername.js
  src/Login/SingUp/index.js
  src/i18n/strings/en_GB.json
  src/i18n/tests/constants.js
  src/i18n/tests/login_translations.test.js
  src/i18n/withI18NTranslation.js
Labels: bug, feature

#307 Fix send request parameters like object
  src/Login/SingUp/LoginPassword.js
Labels: bug

#317 Change build badges
  README.md
Labels: documentation

#319 Fix profile requests
  src/AdminDashboard/Settings/Profiles.js
  yarn.lock
Labels: bug

#324 Real name on the users list
  src/AdminDashboard/Users/UsersItemList.js
  src/AdminDashboard/Users/UsersList.js
Labels: refactor

#327 Run unit tests from Circle CI
  .circleci/config.yml
Labels: ci

#258 Request endpoint search items PluginFlyvemdmInvitation
  src/AdminDashboard/Invitations/InvitationsList.js
Labels: feature, refactor

#338 Add installation section
  README.md
Labels: documentation

#346 Application's compilation
  package.json
  src/i18n/withI18NTranslation.js
Labels: bug, build

#348 Complete package
  package.json
Labels: build

#360 Delete device
  src/AdminDashboard/Devices/Sections/DangerZone.js
Labels: feature

#363 Wipe device
  src/AdminDashboard/Devices/Sections/DangerZone.js
Labels: feature

#377 Update react to '16.2.0'
  package.json
  yarn.lock
Labels: build

#379 Compatibility matrix
  README.md
Labels: documentation
