Repository flyve-mdm/web-mdm-dashboard, pull requests merged in 2018-07, with the labels that each got.

#936 Fix typo error in 'Supervision'
  cypress/integration/Devices.spec.js
  cypress/integration/Fleets.spec.js
  src/hoc/withI18NTranslation/i18n/source_file.json
Labels: bug, refactor

#940 Fix typo error on the add fleet page
  cypress/integration/Devices.spec.js
  cypress/integration/Settings.spec.js
  src/containers/Fleets/components/FleetsContent.js
  src/containers/Invitations/components/InvitationsList.js
Labels: bug, refactor

#942 Update babel-loader to version 7.1.5
  package.json
Labels: build

#943 Update eslint-plugin-flowtype to version 2.49.3
  package.json
Labels: build

#944 Update babel-eslint to version 8.2.5
  package.json
Labels: build

#950 Solve a problem in the system report
  src/containers/Devices/components/Sections/Inventory.js
  src/shared/i18n/source_file.json
Labels: bug

#954 Fix errors on '.htaccess'
  .htaccess
  cypress/screenshots/About -- should navigate in invitations without problemss.png
  cypress/screenshots/Settings -- should login without problems.png
  cypress/screenshots/about_contact.png
  cypress/screenshots/about_noSelection.png
  cypress/screenshots/about_overview.png
  cypress/screenshots/about_term.png
  cypress/screenshots/applications_add.png
  cypress/screenshots/applications_content.png
  cypress/screenshots/applications_edit.png
  cypress/screenshots/applications_noSelection.png
  cypress/screenshots/devices_dangerZone.png
  cypress/screenshots/devices_dangerZone_delete.png
  cypress/screenshots/devices_dangerZone_unenroll.png
  cypress/screenshots/devices_dangerZone_wipe.png
  cypress/screenshots/devices_geolocation.png
  cypress/screenshots/devices_main.png
  cypress/screenshots/devices_noSelection.png
  cypress/screenshots/devices_polices.png
  cypress/screenshots/devices_systemReport.png
  cypress/screenshots/files_add.png
  cypress/screenshots/files_content.png
  cypress/screenshots/files_edit.png
  cypress/screenshots/files_noSelection.png
  cypress/screenshots/fleets_content.png
  cypress/screenshots/fleets_noSelection.png
  cypress/screenshots/home_noData.png
  cypress/screenshots/invitations_logs.png
  cypress/screenshots/invitations_noLogs.png
  cypress/screenshots/invitations_noSelection.png
  cypress/screenshots/login_password.png
  cypress/screenshots/login_userName.png
  cypress/screenshots/logout.png
  cypress/screenshots/settings_changePassword.png
  cypress/screenshots/settings_deleteBrowserData.png
  cypress/screenshots/settings_display.png
  cypress/screenshots/settings_killSession.png
  cypress/screenshots/settings_noSelection.png
  cypress/screenshots/settings_notifications.png
  cypress/screenshots/settings_security.png
  cypress/screenshots/settings_supervision.png
  cypress/screenshots/users_content.png
  cypress/screenshots/users_edit.png
  cypress/screenshots/users_noSelection.png
  package.json
Labels: bug, build

#955 Disable htaccess constructor
  gitlabRunner.sh
Labels: bug, build, ci

#957 Update for htaccess
  gitlabRunner.sh
  htaccess_prod
Labels: bug

#956 Problem with the resize of 'ListWithNavLinks'
  src/components/LayoutListWithNavLinks/index.js
Labels: bug

#960 Change the way to install node modules
  docker/docker-compose.yml
  docker/docker/node/Dockerfile
  docker/docker/node/cliinstall.sh
Labels: build

#962 Add container Apache
  docker/.env
  docker/docker-compose.yml
  docker/docker/apache/Dockerfile
  docker/docker/apache/httpd-vhosts.conf
  docker/docker/apache/httpd.conf
  docker/docker/node/Dockerfile
  docker/docker/node/cliinstall.sh
Labels: build

#963 First selection on the map
  src/containers/Devices/components/Map.js
Labels: bug

#971 Add profile picture
  src/components/IconItemList/index.js
  src/containers/Settings/components/Profiles/index.js
Labels: bug

#973 Fix the validation of empty list menus
  src/containers/Applications/components/ApplicationsList.js
  src/containers/Devices/components/DevicesList.js
  src/containers/Files/components/FilesList.js
  src/containers/Fleets/components/FleetsList.js
  src/containers/Invitations/components/InvitationsList.js
  src/containers/Users/components/UsersList.js
Labels: bug

#975 Unnecessary redirects to the error page
  src/containers/Devices/components/Sections/Geolocation.js
  src/containers/Devices/components/Sections/Main.js
  src/containers/Devices/components/Sections/SystemReport.js
Labels: bug, refactor

#977 Application detail error page
  src/containers/Devices/components/DevicesContent.js
  src/containers/Devices/components/Sections/Applications/ApplicationDetail.js
  src/containers/Devices/components/Sections/Applications/index.js
  yarn.lock
Labels: bug, refactor

#981 Home errors
  src/applications/AdminDashboard/routes.js
  src/containers/HomeDashboard/index.js
Labels: bug

#978 Indexes of the lists
  src/shared/BuildItemList/index.js
Labels: bug, refactor

#980 Change cliinstall
  docker/docker/node/cliinstall.sh
Labels: build, feature

#992 Improve EditMultiple
  src/components/EditMultiple/index.js
Labels: refactor

#993 Fix update state upload file
  src/components/FilesUpload/FilesUpload.js
Labels: refactor

#995 Fix the send feedback
  src/containers/About/components/HelpCenter/Feedback.js
Labels: bug, refactor

#996 Fix help center
  src/containers/About/components/HelpCenter/HelpCenterList.js
Labels: bug, refactor

#1001 Show profile images correctly
  src/components/IconItemList/index.js
Labels: bug

#1004 Disable upload profile images
  src/containers/Settings/components/Profiles/index.js
  src/containers/Users/components/UsersEditOne.js
Labels: refactor

#1008 Use the Credential API only when necessary
  src/containers/SignIn/index.js
Labels: refactor

#1019 Set app version
  package.json
Labels: build

#1022 Fix Jekyll errors on documentation
  ci/scripts/add_header.rb
  ci/scripts/add_space.rb
  ci/scripts/coverage.sh
  ci/scripts/documentation.sh
  ci/scripts/system_install.sh
Labels: ci, documentation

#1025 Fix incorrect format
  docker/docker/node/Dockerfile
  docker/docker/node/cliinstall.sh
  package.json
Labels: build, feature

#1028 Use symbols font family to icons
  src/assets/styles/scss/architecture/5_level_components/_dashboard.scss
  src/assets/styles/scss/architecture/5_level_components/_icons.scss
  src/components/FilesUpload/FilesUploadItemList.js
  src/components/FilesUpload/__tests__/__snapshots__/FilesUploadItemList.snapshot.js.snap
  src/components/Forms/ConstructInputs/index.js
  src/components/Forms/Input/index.js
  src/components/HeaderBreadcrumb/__tests__/__snapshots__/HeaderBreadcrumb.snapshot.js.snap
  src/components/HeaderBreadcrumb/index.js
  src/components/SplitView/IconWithPopper/index.js
  src/containers/About/components/Contact/index.js
  src/containers/About/components/HelpCenter/HelpCenterList.js
  src/containers/Applications/components/ApplicationsContent.js
  src/containers/Applications/components/ApplicationsItemList.js
  src/containers/Applications/components/ApplicationsList.js
  src/containers/Devices/components/DevicesList.js
  src/containers/Devices/components/Sections/Main.js
  src/containers/Files/components/FilesContent.js
  src/containers/Files/components/FilesList.js
  src/containers/Fleets/components/FleetsContent.js
  src/containers/Fleets/components/FleetsList.js
  src/containers/Fleets/components/FleetsTaskItemList.js
  src/containers/Fleets/components/TaskDeployFileList.js
  src/containers/Fleets/components/TasksDeployAppList.js
  src/containers/Fleets/components/TasksRemoveAppList.js
  src/containers/Fleets/components/TasksRemoveFileList.js
  src/containers/Invitations/components/InvitationsList.js
  src/containers/Settings/components/Profiles/index.js
  src/containers/SignUp/index.js
  src/containers/Users/components/UsersContent.js
  src/containers/Users/components/UsersEditOne.js
  src/containers/Users/components/UsersList.js
  src/providers/NotificationsProvider/index.js
Labels: refactor
